export const TOGGLE_TODO = 'TOGGLE_TODO';
export const FETCH_LOADING_TODO = 'FETCH_LOADING_TODO';
export const FETCH_SUCCESS_TODO = 'FETCH_SUCCESS_TODO';
export const FETCH_ERROR_TODO = 'FETCH_ERROR_TODO';